In [1]:
import torch
from gridworld.agent import Agent
from gridworld.rendering import run_simulation_with_rendering
from models.ann import DeepQNet

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print('Device: ', device)

agent = Agent()

model_filename = 'policy_2023-07-17_18-59-33'
gif_filename = f'render_{model_filename}.gif'
state_action_shape = len(agent.actions) + agent.visual_field.shape[0]
loaded_policy = DeepQNet(state_action_shape, 1).to(device)
loaded_policy.load_state_dict(torch.load(model_filename + '.pth'))

duration = run_simulation_with_rendering(loaded_policy, file_name=gif_filename)

pygame 2.5.0 (SDL 2.28.0, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Device:  cpu
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856e-04, -1.1146e-04,
        -1.9869e-04], grad_fn=<CopySlices>)
tensor([-1.6905e-04, -1.3171e-04, -1.2077e-05, -2.5856